//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkerGarageManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangXe
    {
        public HangXe()
        {
            this.Xes = new HashSet<Xe>();
            this.XeDeleteds = new HashSet<XeDeleted>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Xe> Xes { get; set; }
        public virtual ICollection<XeDeleted> XeDeleteds { get; set; }
    }
}
