//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkerGarageManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorkerFileEntities : DbContext
    {
        public WorkerFileEntities()
            : base("name=WorkerFileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChuXe> ChuXes { get; set; }
        public virtual DbSet<HangXe> HangXes { get; set; }
        public virtual DbSet<Xe> Xes { get; set; }
        public virtual DbSet<ChuXeDeleted> ChuXeDeleteds { get; set; }
        public virtual DbSet<HangXeDeleted> HangXeDeleteds { get; set; }
        public virtual DbSet<XeDeleted> XeDeleteds { get; set; }
    }
}
